package io.github.jvcmarcenes.tca.research.knowledge;

public enum Knowledge {
  THEORY_FUNDAMENTALS,
  THEORY_ALCHEMY,
  THEORY_AUROMANCY,
  THEORY_INFUSION,
  THEORY_GOLEM,
  THEORY_ELDRITCH,
  
  OBSERVATION_FUNDAMENTALS,
  OBSERVATION_ALCHEMY,
  OBSERVATION_AUROMANCY,
  OBSERVATION_INFUSION,
  OBSERVATION_GOLEM,
  OBSERVATION_ELDRITCH
}
